package http

const (
	HOST                = "HOST"
	MAX_CONTENT_LENGTH  = "MAX_CONTENT_LENGTH"
	RATE_LIMIT_RPS      = "RATE_LIMIT_RPS"
	RATE_LIMIT_BURST    = "RATE_LIMIT_BURST"
	BUCKET_TTL_SECOND   = "BUCKET_TTL_SECOND"
	IP_WHITELIST        = "IP_WHITELIST"
	IP_BLACKLIST        = "IP_BLACKLIST"
	IDEMPOTENCY_TTL_SEC = "IDEMPOTENCY_TTL_SEC"
)
