package headers

const (
	HEADER_ACCEPT = "Accept"
	HEADER_AUTHORIZATION = "Authorization"
	HEADER_CACHE_CONTROL = "Cache-Control"
	HEADER_CONTENT_LENGTH = "Content-Length"
	HEADER_CONTENT_TYPE = "Content-Type"
	HEADER_COOKIE = "Cookie"
	HEADER_CORS = "Access-Control-Allow-Origin"
	HEADER_IDEMPOTENCY = "Idempotency-Key"
	HEADER_ORIGIN = "Origin"
	HEADER_REFERER = "Referer"
	HEADER_USER_AGENT = "User-Agent"
	HEADER_X_REQUESTED_BY = "X-Requested-By"
	HEADER_X_REQUESTED_WITH = "X-Requested-With"
	HEADER_X_SESSION = "X-Session-Token"
	HEADER_X_CSRF_TOKEN = "X-CSRF-Token"
)

const (
	REQUESTED_BY_API_INT = "API_INTERNAL"
	REQUESTED_BY_API_EXT = "API_EXTERNAL"
	REQUESTED_BY_UI_USER_VERIFIED = "UI_USER_VERIFIED"
	REQUESTED_BY_UI_USER_UNVERIFIED = "UI_USER_UNVERIFIED"
	REQUESTED_BY_USER_ADMIN = "UI_ADMIN"
)

const (
	CLIENT_TYPE_API = "api"
	CLIENT_TYPE_BROWSER = "browser"
)
